[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# atb = { git = "https://github.com/aetheras-io/atb-rs", tag = "v0.12.6", features = ["http", "graphql", "sql", "jwt", "fixtures", "eventsourcing", "serde_utils"] }
actix-web = "4.0.0-beta.12"
actix-cors = "0.6.1"
structopt = "0.3.20"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
futures = "0.3"
chrono = "0.4"
log = "0.4"
env_logger = "0.9"
hex = "0.4"
hyper = { version = "0.14.15", features = ["http1", "runtime", "client"] }