[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.20"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
futures = "0.3"
log = "0.4"
env_logger = "0.9"
hex = "0.4"
hyper = { version = "0.14.15", features = ["http1", "runtime", "client"] }
strum = "0.24"
strum_macros = "0.24"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }